### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by CrazyPython** [cp4k/homebrew-hello-world-2#1]
I don't know how else to contact you guys, but I just wanted to say hello.

**Comment by CrazyPython** [comment]
I've had lots of progress since the forum closed, like experienced Java developer, deploying app using Django + Gunicorn + Foreman.

**Comment by cartr** [comment]
Hi there! It's nice to hear from you again. Glad to see you're making progress in the world of programming!

In the future, you can contact us at cp4khelp@gmail.com. I'm closing this issue since it isn't a problem with our Mac Homebrew package.

**Comment by CrazyPython** [comment]
I understand. However, I haven't ever received a reply from that email.
